### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by ChrisRackauckas** [pkofod/PlusPlus.jl#2]
How am I supposed to trust your package without some CI?

**Comment by pkofod** [comment]
I turned off my computer. Will add CI and coverage tomrrow

**Comment by pkofod** [comment]
Just need appveyor

**Comment by ChrisRackauckas** [comment]
Windows neglect.

**Comment by pkofod** [comment]
appveyor and travis running... I even added coveralls and codecov.. closing
